kind: Service
apiVersion: v1
metadata:
  namespace: PLACEHOLDER_NAMESPACE
  name: PLACEHOLDER_SERVICE_NAME
spec:
  selector:
    app: PLACEHOLDER_SERVICE_NAME
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: PLACEHOLDER_NAMESPACE
  name: PLACEHOLDER_SERVICE_NAME
  annotations:
    haproxy.ingress.kubernetes.io/ssl-redirect: "true"
    haproxy.ingress.kubernetes.io/ssl-redirect-port: "443"
spec:
  ingressClassName: haproxy-batman
  rules:
  - host: n8n.batman.dev.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: PLACEHOLDER_SERVICE_NAME
            port:
              number: 80
  tls:
  - hosts:
    - n8n.batman.dev.com
    secretName: wildcard.batman.dev.com

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: PLACEHOLDER_NAMESPACE
  labels:
    app: PLACEHOLDER_SERVICE_NAME
  name: PLACEHOLDER_SERVICE_NAME
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: PLACEHOLDER_SERVICE_NAME
  template:
    metadata:
      labels:
        app: PLACEHOLDER_SERVICE_NAME
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: n8n
          image: n8nio/n8n:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5678
              name: http-n8n
              protocol: TCP
          env:
            - name: N8N_HOST
              value: n8n.batman.com
            - name: N8N_PORT
              value: "5678"
            - name: WEBHOOK_URL
              value: "https://n8n.batman.dev.com"
            - name: N8N_EDITOR_BASE_URL
              value: "https://n8n.batman.dev.com"
            - name: N8N_PROTOCOL
              value: "https"
            - name: N8N_TELEMETRY_ENABLED
              value: "false"
            - name: N8N_DIAGNOSTICS_ENABLED
              value: "false"
            - name: N8N_VERSION_NOTIFICATIONS_ENABLED
              value: "false"
            - name: N8N_HIRING_BANNER_ENABLED
              value: "false"
            - name: N8N_PERSONALIZATION_ENABLED
              value: "false"
            - name: HTTP_PROXY
              value: ""
            - name: HTTPS_PROXY
              value: ""
            - name: NO_PROXY
              value: "localhost,127.0.0.1,.svc.cluster.local"
            - name: DB_SQLITE_POOL_SIZE
              value: "5"
            - name: N8N_RUNNERS_ENABLED
              value: "true"
            - name: N8N_BLOCK_ENV_ACCESS_IN_NODE
              value: "false"
            - name: N8N_GIT_NODE_DISABLE_BARE_REPOS
              value: "true"
            - name: N8N_METRICS_INCLUDE_X_FORWARDED_FOR
              value: "true"
            - name: N8N_TRUSTED_PROXIES
              value: "0.0.0.0/0"
            - name: N8N_ENABLE_PROXY
              value: "true"
            - name: N8N_PROXY_HOPS
              value: "1"
            - name: N8N_EMAIL_MODE
              value: "smtp"
            - name: N8N_SMTP_HOST
              value: "email.batman.com"
            - name: N8N_SMTP_PORT
              value: "25"
            - name: N8N_SMTP_SSL
              value: "false"
            - name: N8N_SMTP_STARTTLS
              value: "true"
            - name: N8N_SMTP_USER
              value: ""
            - name: N8N_SMTP_PASS
              value: ""
            - name: N8N_SMTP_SENDER
              value: "batman@justiceleague.com"
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 5678
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 5678
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: PLACEHOLDER_NAMESPACE
  name: n8n-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi